#!/usr/bin/env bash
#
# Launch dcode with the evroc provider and the dynamic_tools plugin.
#
# Usage:
#   ./run.sh [dcode args...]
#
# Environment:
#   EVROC_API_KEY    API key for the evroc platform (required).
#   EVROC_MODEL      Model identifier (optional, default: zai-org/GLM-5.2).
#   EVROC_BASE_URL   Override the evroc base URL (optional).
#   DCODE_NO_SANDBOX Set to any non-empty value to launch unsandboxed.
#
# The virtual environment is always taken from this script's directory via
# `uv --project`, which discovers the venv without changing the working
# directory (`uv --directory` is the flag that cds).
#
# Auto-loaded from ~/.metalgate/.env if present; the environment takes
# precedence over the file.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Environment ------------------------------------------------------------
ENV_FILE="${HOME}/.metalgate/.env"
if [[ -f "${ENV_FILE}" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "${ENV_FILE}"
    set +a
fi

: "${EVROC_API_KEY:?EVROC_API_KEY is required. Set it to your evroc platform API key.}"
export EVROC_API_KEY
export EVROC_MODEL="${EVROC_MODEL:-zai-org/GLM-5.2}"
export EVROC_BASE_URL="${EVROC_BASE_URL:-https://models.think.cloud.evroc.com/v1}"

export DEEPAGENTS_CODE_EXPERIMENTAL=1
export DEEPAGENTS_HOME="${SCRIPT_DIR}/.metalgate"
mkdir -p "${DEEPAGENTS_HOME}"

# --- Install ----------------------------------------------------------------
uv --project "${SCRIPT_DIR}" sync --quiet

# Fetch models into .evroc/models.json for the /model switcher. A failed
# fetch is non-fatal: dcode launches against a stale file if one exists.
set +e
uv --project "${SCRIPT_DIR}" run python "${SCRIPT_DIR}/scripts/fetch_models.py"
set -e

# --- config.toml ------------------------------------------------------------
# No `models` list: dcode auto-discovers from evroc/data/_profiles.py (which
# reads .evroc/models.json), so the switcher always reflects the live API.
cat > "${DEEPAGENTS_HOME}/config.toml" <<EOF
# Generated by run.sh — do not edit manually.

[models]
default = "evroc:${EVROC_MODEL}"

[models.providers.evroc]
display_name = "evroc"
api_key_env = "EVROC_API_KEY"
base_url = "${EVROC_BASE_URL}"
class_path = "evroc:ChatModel"
enabled = true

[models.providers.evroc.params]
# Most OpenAI-compatible gateways only implement Chat Completions, not Responses.
use_responses_api = false

[models.providers.evroc.profile]
tool_calling = true
EOF

# --- Sandbox ----------------------------------------------------------------
# Run under the seatbelt sandbox on macOS unless explicitly disabled. This
# keeps the sandbox dependency tied to the platform that provides it and
# leaves the unsandboxed path a one-line opt-out.
SANDBOX_ARGS=()
if [[ "$(uname -s)" == "Darwin" && -z "${DCODE_NO_SANDBOX:-}" ]]; then
    SANDBOX_ARGS=(--sandbox seatbelt)
fi

# --- Marketplace + plugin (both commands are idempotent) --------------------
MARKETPLACE_DIR="${SCRIPT_DIR}/marketplace"
uv --project "${SCRIPT_DIR}" run dcode plugin marketplace add "${MARKETPLACE_DIR}" >/dev/null
uv --project "${SCRIPT_DIR}" run dcode plugin install "dynamic_tools@evroc-extensions" >/dev/null

# --- Launch -----------------------------------------------------------------
# `${SANDBOX_ARGS[@]+"${SANDBOX_ARGS[@]}"}` is the bash-3.2-safe empty-array
# expansion: macOS ships bash 3.2, where `"${a[@]}"` under `set -u` errors on
# an empty array ("unbound variable"). The `${a[@]+...}` guard expands to
# nothing when the array is empty, and to the full array otherwise.
exec uv --project "${SCRIPT_DIR}" run dcode ${SANDBOX_ARGS[@]+"${SANDBOX_ARGS[@]}"} "$@"
